#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftArm1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftArm2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftArm3,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightArm1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightArm3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#pragma platform(VEX)

#include "Vex_Competition_Includes.c" //Main competition Background Code

void pre_auton()
{
    bStopTasksBetweenModes = true;
}

// Sets the speed of the left side of the drive train
void leftDrive(int speed){
    motor[frontLeft] = speed;
    motor[backLeft] = speed;
}

// Sets the speed of the right side of the drive train
void rightDrive(int speed){
    motor[frontRight] = speed;
    motor[backRight] = speed;
}

// Raises and lowers the arm
void moveArm(int speed){
    motor[rightArm1] = speed;
    motor[rightArm2] = speed;
    motor[rightArm3] = speed;
    motor[leftArm1] = speed;
    motor[leftArm2] = speed;
    motor[leftArm3] = speed;
}

task autonomous(){

}

task usercontrol(){
    while(true){
        // Tank Drive
        leftDrive(vexRT[Ch3]);
        rightDrive(vexRT[Ch2]);

        int armSpeed = 0;

        // Arm Control
        if (vexRT[Btn7UXmtr2] == 1) {
            armSpeed = 127;
        } else if (vexRT[Btn7DXmtr2] == 1) {
            armSpeed = -127;
        }

        moveArm(armSpeed);
    }
}
